---
- hosts: webservers
  tasks:
    - name: install httpd
      package: name=httpd state=installed
    - name: configure
      shell: "echo hello Yesssssssssssss I did it!!!!!!!!!!!!!  >> /var/www/html/index.html"
    - name: start service
      service: name=httpd state=started

